[time_control]
interval_seconds = 21600 # time interval between incoming data from the time series data, which is the interval (secs) between times in the lateral boundary condition file

[time_control.history_file]
history_interval = [180, 180, 60] # The interval in minutes that the output should be written out for each domain
history_begin = 0 # Number of mins from the start of the run in which the history output file (wrfout) is written
n_hours_per_file = 24

[time_control.summary_file]
output_diagnostics = 0 # A value of 1 makes the output
auxhist3_interval = 1440 # Number of minutes to output
n_hours_per_file = 240

[time_control.z_level_file]
z_lev_diags = 1 # A value of 1 makes the output
z_levels = [20, 30, 80, 150, 200, 350, 500, 750, 1000, 1300, 1600, 2000, 2500, 3000, 4000, 5000, 7000, 10000] # Heights in meters above ground. Might not work at values < 30. Change dzbot in physics to 30 for 20 m height to work.

[remote]
type = 's3'
provider = 'Mega'
endpoint = 'https://s3.ca-west-1.s4.mega.io'
access_key_id = ''
secret_access_key = ''
path = '/data/wrf/test1/'
